/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package receptionist;

/**
 *
 * @author USER
 */
public class Appointment extends javax.swing.JFrame {

    /**
     * Creates new form Appointment
     */
    public Appointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1Cardio = new javax.swing.JButton();
        jButton1Orthopedic = new javax.swing.JButton();
        jButton1Nephrology = new javax.swing.JButton();
        jButton1Neurology = new javax.swing.JButton();
        jButton2Gynecology = new javax.swing.JButton();
        jButton1B = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1Cardio.setBackground(new java.awt.Color(0, 0, 0));
        jButton1Cardio.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1Cardio.setForeground(new java.awt.Color(102, 102, 255));
        jButton1Cardio.setText("Cardiology");
        jButton1Cardio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CardioActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Cardio);
        jButton1Cardio.setBounds(410, 50, 150, 40);

        jButton1Orthopedic.setBackground(new java.awt.Color(0, 0, 0));
        jButton1Orthopedic.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1Orthopedic.setForeground(new java.awt.Color(255, 102, 255));
        jButton1Orthopedic.setText("Orthopedic");
        jButton1Orthopedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1OrthopedicActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Orthopedic);
        jButton1Orthopedic.setBounds(410, 110, 150, 40);

        jButton1Nephrology.setBackground(new java.awt.Color(0, 0, 0));
        jButton1Nephrology.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1Nephrology.setForeground(new java.awt.Color(255, 102, 102));
        jButton1Nephrology.setText("Nephrology");
        jButton1Nephrology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1NephrologyActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Nephrology);
        jButton1Nephrology.setBounds(410, 170, 150, 40);

        jButton1Neurology.setBackground(new java.awt.Color(0, 0, 0));
        jButton1Neurology.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1Neurology.setForeground(new java.awt.Color(51, 255, 51));
        jButton1Neurology.setText("Neurology");
        jButton1Neurology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1NeurologyActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Neurology);
        jButton1Neurology.setBounds(410, 230, 150, 40);

        jButton2Gynecology.setBackground(new java.awt.Color(0, 0, 0));
        jButton2Gynecology.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2Gynecology.setForeground(new java.awt.Color(0, 153, 153));
        jButton2Gynecology.setText("Gynecology");
        jButton2Gynecology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2GynecologyActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2Gynecology);
        jButton2Gynecology.setBounds(410, 300, 150, 40);

        jButton1B.setBackground(new java.awt.Color(0, 0, 0));
        jButton1B.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1B.setForeground(new java.awt.Color(255, 51, 51));
        jButton1B.setText("Back");
        jButton1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1B);
        jButton1B.setBounds(510, 440, 100, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\L.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 620, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(632, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BActionPerformed
        // TODO add your handling code here:
        new RJFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1BActionPerformed

    private void jButton2GynecologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2GynecologyActionPerformed
        // TODO add your handling code here:
        new Gyne().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2GynecologyActionPerformed

    private void jButton1NephrologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1NephrologyActionPerformed
        // TODO add your handling code here:
        new Neph().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1NephrologyActionPerformed

    private void jButton1OrthopedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1OrthopedicActionPerformed
        // TODO add your handling code here:
        new Ortho().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1OrthopedicActionPerformed

    private void jButton1CardioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CardioActionPerformed
        // TODO add your handling code here:
        new Cardi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1CardioActionPerformed

    private void jButton1NeurologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1NeurologyActionPerformed
        // TODO add your handling code here:
        new Neur().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1NeurologyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1B;
    private javax.swing.JButton jButton1Cardio;
    private javax.swing.JButton jButton1Nephrology;
    private javax.swing.JButton jButton1Neurology;
    private javax.swing.JButton jButton1Orthopedic;
    private javax.swing.JButton jButton2Gynecology;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
