/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package receptionist;

import java.io.File;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import javax.swing.ButtonGroup;

/**
 *
 * @author USER
 */
public class Cardi extends javax.swing.JFrame {

    /**
     * Creates new form Cardi
     */
    public Cardi() {
        initComponents();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1Patientname = new javax.swing.JTextField();
        jTextField1Gender = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1Age = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1Seat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel4Guardianname = new javax.swing.JLabel();
        jTextField1Doctorname = new javax.swing.JTextField();
        jLabel4Contacno = new javax.swing.JLabel();
        jTextField1Contacno = new javax.swing.JTextField();
        jLabel4Address = new javax.swing.JLabel();
        jTextField1Address = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2Confirm = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1Patientname.setBackground(new java.awt.Color(0, 153, 0));
        jTextField1Patientname.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField1Patientname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1PatientnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Patientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 210, 27));

        jTextField1Gender.setBackground(new java.awt.Color(0, 153, 0));
        jTextField1Gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1GenderActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 90, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Patient's Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 27));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Gender :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 27));

        jTextField1Age.setBackground(new java.awt.Color(0, 153, 0));
        jTextField1Age.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jTextField1Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1AgeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 60, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Age :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 40, 27));

        jTextField1Seat.setBackground(new java.awt.Color(0, 153, 0));
        jTextField1Seat.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jTextField1Seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1SeatActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Serial- No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 20));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 0, 0));
        jRadioButton1.setText("Dr.Kamal Hossain");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 160, 30));

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 0, 0));
        jRadioButton2.setText("Dr.Sumaya Jannat");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(204, 0, 0));
        jRadioButton3.setText("Dr.Mahmuda Khatun");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(204, 0, 0));
        jRadioButton4.setText("Dr.Jakir Alam");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 130, -1));

        jLabel4Guardianname.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4Guardianname.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4Guardianname.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4Guardianname.setText("Doctor's Name:");
        getContentPane().add(jLabel4Guardianname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 22));

        jTextField1Doctorname.setBackground(new java.awt.Color(0, 153, 0));
        jTextField1Doctorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1DoctornameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Doctorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 190, 30));

        jLabel4Contacno.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4Contacno.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4Contacno.setText("Contac no.:");
        getContentPane().add(jLabel4Contacno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 20));

        jTextField1Contacno.setBackground(new java.awt.Color(0, 153, 0));
        jTextField1Contacno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ContacnoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Contacno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 163, 30));

        jLabel4Address.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4Address.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4Address.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4Address.setText("Address :");
        getContentPane().add(jLabel4Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 80, -1));

        jTextField1Address.setBackground(new java.awt.Color(0, 153, 0));
        jTextField1Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1AddressActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 259, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 0, 90, 40));

        jButton2Confirm.setBackground(new java.awt.Color(0, 153, 0));
        jButton2Confirm.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2Confirm.setForeground(new java.awt.Color(153, 0, 51));
        jButton2Confirm.setText("Confirm");
        jButton2Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 90, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\HC4.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        setSize(new java.awt.Dimension(775, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTextField1PatientnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1PatientnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1PatientnameActionPerformed

    private void jTextField1GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1GenderActionPerformed

    private void jTextField1AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1AgeActionPerformed

    private void jTextField1SeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1SeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1SeatActionPerformed

    private void jTextField1DoctornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1DoctornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1DoctornameActionPerformed

    private void jTextField1ContacnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ContacnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ContacnoActionPerformed

    private void jTextField1AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1AddressActionPerformed

    private void jButton2ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ConfirmActionPerformed
        // TODO add your handling code here:
        String Seat=jTextField1Seat.getText();
        String PatientName = jTextField1Patientname.getText();
        String Gender = jTextField1Gender.getText();
        String Age = jTextField1Age.getText();
        
        String DoctorName=jTextField1Doctorname.getText();
        String Contac_no=jTextField1Contacno.getText();
        String Address=jTextField1Address.getText();
       
        File file = new File ("cardiology.txt");

        try {
            
            FileOutputStream f = new FileOutputStream(file,true);
            PrintWriter writer = new PrintWriter (f);
            writer .append(Seat+" "+PatientName+" "+Gender+" "+Age+" "+" "+DoctorName+" "+Contac_no+" "+Address+"\r\n");
            writer.close();
            f.close();
            new Appointment().setVisible(true);
            this.dispose();
            
           
        } 
        catch (Exception ex) {
            System.out.println(ex+"\n");
        }
        
        
    }//GEN-LAST:event_jButton2ConfirmActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1Doctorname.setText(jRadioButton1.getText());
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        jTextField1Doctorname.setText(jRadioButton4.getText());
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         jTextField1Doctorname.setText(jRadioButton2.getText());
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
         jTextField1Doctorname.setText(jRadioButton3.getText());
    }//GEN-LAST:event_jRadioButton3ActionPerformed

      private void groupButton()
    {
        ButtonGroup a=new ButtonGroup();
        a.add(jRadioButton1);
        a.add(jRadioButton2);
        a.add(jRadioButton3);
        a.add(jRadioButton4);
    }
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Appointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cardi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cardi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cardi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cardi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cardi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2Confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4Address;
    private javax.swing.JLabel jLabel4Contacno;
    private javax.swing.JLabel jLabel4Guardianname;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1Address;
    private javax.swing.JTextField jTextField1Age;
    private javax.swing.JTextField jTextField1Contacno;
    private javax.swing.JTextField jTextField1Doctorname;
    private javax.swing.JTextField jTextField1Gender;
    private javax.swing.JTextField jTextField1Patientname;
    private javax.swing.JTextField jTextField1Seat;
    // End of variables declaration//GEN-END:variables

    
    
}
