/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package receptionist;

/**
 *
 * @author USER
 */
public class RJFrame extends javax.swing.JFrame {

    /**
     * Creates new form RJFrame
     */
    public RJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Addmitpatient = new javax.swing.JButton();
        jButton1Appointments = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1Addmitpatient.setBackground(new java.awt.Color(0, 102, 0));
        jButton1Addmitpatient.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1Addmitpatient.setForeground(new java.awt.Color(51, 0, 51));
        jButton1Addmitpatient.setText("Admit - Patient");
        jButton1Addmitpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AddmitpatientActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Addmitpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 220, 50));

        jButton1Appointments.setBackground(new java.awt.Color(0, 102, 0));
        jButton1Appointments.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1Appointments.setForeground(new java.awt.Color(51, 0, 51));
        jButton1Appointments.setText("Appointments");
        jButton1Appointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AppointmentsActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Appointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 50));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 51));
        jButton1.setText("Search - Patient -Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 260, 50));

        jButton2.setBackground(new java.awt.Color(0, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 51));
        jButton2.setText("Back");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 90, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Hp2.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 400));

        setSize(new java.awt.Dimension(693, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1AddmitpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AddmitpatientActionPerformed
        // TODO add your handling code here
        new AddPatient().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1AddmitpatientActionPerformed

    private void jButton1AppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AppointmentsActionPerformed
        // TODO add your handling code here:
        new Appointment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1AppointmentsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new PSearch_Info().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Addmitpatient;
    private javax.swing.JButton jButton1Appointments;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
